fix: app-api, add leaderboard-preloader,
babylon-game/practicum_15puzzle_babylon pull request #8
Opened 2022-09-13 05:35 UTC by bmazurme

2022-09-14 08:40 UTC, rkkmkkfx requested changes

2022-09-14 08:40 UTC, rkkmkkfx commented on src/store/api/appApi/index.ts
> +const baseQuery = fetchBaseQuery({ baseUrl: 'https://ya-praktikum.tech/api/v2/' });
стандартный fetch придется все равно заменять, когда проект переедет на server-side rendering, плюс непонятно, для чего две разных query функции использовать, так как у axios есть весь необходимый функционал

2022-09-14 08:40 UTC, rkkmkkfx commented on src/pages/leaderboard.tsx
> -export default withUser(LeaderboardPage);
user нужен на всех страницах, иначе в header вместо UserMenu будут кнопки signin/signup. Если на странице не нужна проверка авторизации, то вторым аргументом можно передать false

2022-09-14 20:02 UTC, Bmazurm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить Leaderboard API](https://trello.com/c/75bkNZRA/24-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-leaderboard-api)

2022-09-16 12:16 UTC, Kventi111 approved these changes

2022-09-18 06:03 UTC, rkkmkkfx approved these changes

2022-09-28 09:31 UTC, Kventi111 approved these changes

2022-09-28 18:44 UTC, merged